<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UseWPF>true</UseWPF>
	</PropertyGroup>

	<ItemGroup>
	  <None Remove="Resources\File_icon.png" />
	  <None Remove="Resources\Import_icon.png" />
	  <None Remove="Resources\info_icon.png" />
	  <None Remove="Resources\logo.ico" />
	  <None Remove="Resources\logo.png" />
	  <None Remove="Resources\logo_light.png" />
	  <None Remove="Resources\logo_white.png" />
	  <None Remove="Resources\settings_icon.png" />
	</ItemGroup>

	<ItemGroup>
	  <COMReference Include="pfcls">
	    <WrapperTool>tlbimp</WrapperTool>
	    <VersionMinor>0</VersionMinor>
	    <VersionMajor>1</VersionMajor>
	    <Guid>176453f2-6934-4304-8c9d-126d98c1700e</Guid>
	    <Lcid>0</Lcid>
	    <Isolated>false</Isolated>
	    <EmbedInteropTypes>true</EmbedInteropTypes>
	  </COMReference>
	</ItemGroup>

	<ItemGroup>
		<Folder Include="Models\" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="ClosedXML" Version="0.105.0" />
		<PackageReference Include="Ookii.Dialogs.Wpf" Version="5.0.1" />
		<PackageReference Include="System.Management" Version="9.0.8" />
	</ItemGroup>

	<ItemGroup>
	  <Resource Include="Resources\File_icon.png">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </Resource>
	  <Resource Include="Resources\Import_icon.png">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </Resource>
	  <Resource Include="Resources\info_icon.png">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </Resource>
	  <Resource Include="Resources\logo.ico">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </Resource>
	  <Resource Include="Resources\logo.png">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </Resource>
	  <Resource Include="Resources\logo_light.png">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </Resource>
	  <Resource Include="Resources\settings_icon.png">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </Resource>
	</ItemGroup>

</Project>
